SRC_DIR = ./src
PYSRC_DIR = ./pysrc
BUILD_DIR = ./build
DOCS_DIR = ./docs
README = ./README.md

DOCS_SRC = $(wildcard $(SRC_DIR)/*.cpp) $(wildcard $(SRC_DIR)/*.hpp) $(wildcard $(PYSRC_DIR)/*.py) $(README)
DOCS_TGT = $(DOCS_DIR)/html $(DOCS_DIR)/latex

.PHONY: docs
docs: $(DOCS_TGT)

$(DOCS_TGT): $(DOCS_SRC)
	cd $(DOCS_DIR); doxygen
	sleep 1
	cd $(DOCS_DIR)/latex/; make

.PHONY: clean
clean:
	-rm -r $(DOCS_DIR)/latex/
	-rm -r $(DOCS_DIR)/html/
