SRC_DIR = ./src
BUILD_DIR = ./build
DOCS_DIR = ./docs

DOCS_SRC = $(wildcard $(SRC_DIR)/*.cpp) $(wildcard $(SRC_DIR)/*.hpp)
DOCS_TGT = $(DOCS_DIR)/html $(DOCS_DIR)/latex

.PHONY: docs
docs: $(DOCS_TGT)

$(DOCS_TGT): $(DOCS_SRC)
	cd $(DOCS_DIR); doxygen
	cd $(DOCS_DIR)/latex/; make

.PHONY: clean
clean:
	-rm -r $(DOCS_DIR)/latex/
	-rm -r $(DOCS_DIR)/html/
